# vim:ft=yaml.ansible
---
- name: "Install postgresql-server"
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: "Install python3-pip"
  ansible.builtin.apt:
    name: "python3-pip"
    state: "present"

- name: "Install python postgres adapter"
  ansible.builtin.pip:
    name: "psycopg2-binary"
    executable: "/usr/bin/pip3"
    version: 2.8.6
    state: "present"

- name: "Set user postgres a password"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    db: postgres
    name: postgres
    password: "{{ postgres_password }}"

- name: Create a new database with name database_name
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ database_name }}"
