# vim:ft=yaml.ansible
---
# tasks file for docker
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Set up docker repository
  ansible.builtin.apt_repository:
    repo:
      deb [arch=arm64] https://download.docker.com/linux/debian {{
      ansible_distribution_release }} stable
    state: present

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Ensure Docker is started and enabled on boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
